### ISSUE TITLE
Review mail server configuration and document its maintenance

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#106]
Ensure notes are published in https://docs.webplatform.org/wiki/WPD:Infrastructure/procedures/Maintaining_email_services
## To cover
- Look for probable loose ends in the config
  - app1.staging.wpdn sends alert, mail bounces it and doesn’t know where to send it back. Should it keep it locally instead?
  - etc... 
- Accept incoming mail for relay only from our network
- Before relaying, pass through SpamAssassin
- Filter system mails from our network, make them viewable in a protected mailman/hypermail viewer, 
- Document how to debug mail from both clients (our network nodes using Exim4) and the mail relay (using Postfix + Amavis + OpenDKIM + SpamAssassin + ClamAV + etc)
## TODO
- [x] Document how to manage the mail queue
  - [x] ... the deferred messages
  - [ ] ... delete outdated messages
  - [ ] ... double check DNS (SPF, TXT, DKIM, DMARC, etc) entries
- [ ] Review server configuration
  - [ ] Allow relay exclusively from private network and known external IPs
  - [ ] TLS/ESMTPS etc
  - [ ] SpamAssassin to run on every outgoing messages. (e.g. In case its a comment spam from a user)
- [ ] Simplify? 
- Ensure similar operations are documented with both exim4 and postfix
## Re-evaluate; keep Exim+Postfix or...?
- https://github.com/baudehlo/Haraka
## Reference
- http://www.postfix.org/STANDARD_CONFIGURATION_README.html
- http://postfixmail.com/blog/
- http://www.cyberciti.biz/faq/exim-remove-all-messages-from-the-mail-queue/
- http://www.akadia.com/services/postfix_spamassassin.html

**Comment by renoirb** [comment]
2h spent.

Issue was raised by somebody on the WebPlatform admin mailing list that he never got the confirmation email.  After reviewing mail.webplatform.org setup, there were many deferred messages.

Diagnosis:
- :+1: MX record points correctly to public IP address
- :-1:  VM security groups was blocking ALL SMTP traffic. This could flag our SMTP relay as potential spammer (adjusted).
- :-1: SPF record (`dig TXT webplatform.org`) was too strict, had only two IPs, could use a range of Public IPs instead (adjusted)
- :-1: SOA record (`dig SOA webplatform.org`) was not giving a valid email address. Was giving `hostmaster@org` instead of `team-webplatform-admin@w3.org` (adjusted)

**Comment by renoirb** [comment]
Commands pastebin:

## Postfix
- Display one message
  
  ```
  postcat -q BD2E92036A
  ```
- List the mail queue
  
  ```
  postqueue -p
  ```
- Purge messages —Don’t do that to liberally, only to known email messages patterns that you know are obselete—
  
  ```
  postqueue -p | grep ubuntu@webplatform.org | awk '{print $1}' | tr -d '*' | while read mid ; do postsuper -d $mid ; done
  ```
- Test if an email alias (e.g. root@webplatform.org) works (e.g. `root@webplatform.org` to send to `team-webplatform-foo@w3.org`)
  
  ```
  postmap -q 'root' hash:/etc/postfix/virtual && echo OK || echo 'No match found'
  ```

## Exim
- Display one message, body, headers
  
  ```
  exim -Mvb 1YLjcr-0000es-0R
  exim -Mvh 1YLjcr-0000es-0R
  ```
- List the mail queue
  
  ```
  mailq
  ```
- Reprocess the queue
  
  ```
  exim -q
  exim -qf
  ```
- Delete one message
  
  ```
  exim -Mrm 1YLjcr-0000es-0R
  ```
- Delete the whole queue
  
  ```
  exiqgrep -i | xargs exim -Mrm
  ```

Ref: http://www.electrictoolbox.com/exim-delete-message/

**Comment by renoirb** [comment]
Spent 1h to revise if things looks OK

**Comment by renoirb** [comment]
Maybe I should explode this task a bit.   Moved documentation from this issue into https://docs.webplatform.org/wiki/WPD:Infrastructure/procedures/Maintaining_email_services
