### ISSUE TITLE
Upgrade webat25.org current environment so it can safely stay on old production until May

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#129]
Make sure old production is using recent versions and has security patches done.
## Tasks
- [x] Backup image uploads, upload to production backup storage
- [x] Upgrade server packages
- [x] Ensure database setup will hold
- [x] During recent Piwik upgrade from 1.x to 2.x, tracking code changed, apply it to webat25.org

**Comment by renoirb** [comment]
Worked 3h
