### ISSUE TITLE
Automate MediaWiki (docs) deployment

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#13]
More of a rework, though.
## Tasks

Continuing work started in webplatform/ops#12
-  [ ] Ensure we can watch at least one repository and find a way to trigger automatic update from the parent.
- [x] Double check 2015-01-12 `$wgSquidServers` changes gives better results
- [ ] Find what to listen to changes in relation to the wiki, which should we pick: an extension, then build the full package?
- [ ] Automation setup, once figured out in webplatform/ops#80
## Related
- webplatform/ops#80

**Comment by renoirb** [comment]
Also reworked email body to be close to [Wikipedia’s](https://en.wikipedia.org/wiki/MediaWiki:Confirmemail_body) by editing our own [MediaWiki:Confirmemail_body](https://docs.webplatform.org/wiki/MediaWiki:Confirmemail_body)

**Comment by renoirb** [comment]
Moved away few tasks into sizable chunks.

**Comment by renoirb** [comment]
Related to epic webplatform/ops#80

**Comment by renoirb** [comment]
Mistakenly closed. This task was about the automation (i.e. detect changes, pull them, run scripts, deploy). My bad.

**Comment by renoirb** [comment]
Mistakenly closed. This task was about the automation (i.e. detect changes, pull them, run scripts, deploy). My bad. Migrated what’s done into webplatform/ops#130 instead
