### ISSUE TITLE
Review MediaWiki (docs) deployment scripts

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#130]
More of a rework, though.
## Tasks

Continuing work started in webplatform/ops#12
- [x] Memcached for object and page cache
- [x] Redis for sessions
- [x] Ensure install is a few commands as possible
- [x] Ensure account creation confirmation email has SSL
- [x] Configuration adjusts depending of the top level domain
- [x] Ensure SSL is enabled between backend and Fastly, and Fastly and visitor

**Comment by renoirb** [comment]
Forked off from webplatform/ops#13
