### ISSUE TITLE
Review (once more) MediaWiki configuration

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#131]
While working on sprint, the following "nice to have" weren’t worked on. Here are other things we can do to improve our setup.
## Tasks
- [ ] Ensure Redis uses password
- [ ] Redirect old image pattern to new, e.g. http://docs.webplatform.org/w/images/7/7a/language.png http://static.webplatform.org/w/public/7/7a/language.png see also #43 and #58
- [ ] Ensure reCAPTCHA still works under SSL, related to #42
- [ ] Redirect former docs.webpaltform.org/w/img/ to www
- [ ] Redirect what had been served from static.webplatform.org to www
- [ ] Ensure gzip is enabled edge to client but not origin to Fastly. At least for wiki, so ESI will work
- [ ] Setup MediaWiki to use ElasticSearch #122 
- [ ] Review how to separate our configurations from mediawiki code
- Review/use https://gist.github.com/WebPlatformDocs/e91bbfdc81dd85c2401a
## Reference
- https://github.com/wikimedia/operations-mediawiki-config
- https://github.com/wikimedia/mediawiki/blob/wmf/1.25wmf22/.gitmodules
- https://github.com/wikimedia/wmf-utils
-
