### ISSUE TITLE
Keep MediaWiki session lifetime in sync with cookie

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#135]
Cookies in the browser that doesn’t hold a valid session key can lead to make the Varnish server to think it cannot serve cached content. There must be a way to check quickly in the backend if the session identifier still has a valid session and if not, communicate (in some way?) to serve a cached version.

This applies to MediaWiki but could be documented on how it works.

Objective is to increase cache hit ratio.
## Tasks
- [ ] Figure out how to check if a session key holds a valid session (in MW)
- [ ] From the backend, can we ask the browser to delete the cookie if it’s proven to be a no longer valid session key?
- [ ] How to configure PHP/Redis/Cookies to have same lifetime
## Reference
- http://superuser.com/questions/204905/mediawiki-increase-session-timeout
- http://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes

**Comment by renoirb** [comment]
Dropping the ball, we won’t use. Refer to webplatform/ops#177
