### ISSUE TITLE
Create publican runner to use as an utility to compile on hooks

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#153]
## Thoughts/questions
- How about publican only dumps generated HTML into a directory so that the frontend servers reads from that directory directly.
## Tasks
- [x] Find way to make container write generated HTML into `data/`
- [x] Make sure it runs as close as @darobin designed it
- [x] Build container steps in a Makefile
- [x] Create Docker Hub organization
- [x] Commit and push first image
- [x] Document how to use
## Related
- webspecs/publican#21 Run publican in a Container ("Task based docker")

**Comment by renoirb** [comment]
Created Docker container and pushed to new Docker Hub organization registry "webspecs".

Container: https://registry.hub.docker.com/u/webspecs/publican/

Diff: https://github.com/webplatform/publican/compare/task-based...webplatform:task-based-docker

**Comment by renoirb** [comment]
Created PR https://github.com/webspecs/publican/pull/19

**Comment by renoirb** [comment]
Could poke a build with this curl, but something’s off. I hope not anybody can make such requests otherwise it’d make a DoS surface :(

  curl -H "Content-Type: application/json" -XPOST http://192.168.59.103:49156/hook -d '{"branch": "master", "repository": {"name":"the-index", "owner": {"name": "webspecs"}}}'

**Comment by renoirb** [comment]
Could poke a build with this curl, but something’s off. I hope not anybody can make such requests otherwise it’d make a DoS surface :(

```
curl -H "Content-Type: application/json" -XPOST http://192.168.59.103:49156/hook -d '{"branch": "master", "repository": {"name":"the-index", "owner": {"name": "webspecs"}}}'
```

**Comment by renoirb** [comment]
@darobin, ping! Can we talk about this?

**Comment by renoirb** [comment]
Things are going well. Except an issue with phantomjs that hangs and breaks when we use specs that uses respec (e.g. rangefinder spec).

![publican-broken-at-rangefinder](https://cloud.githubusercontent.com/assets/296940/7576791/aa99f7b2-f80f-11e4-9447-3152be5edcd5.png)

**Comment by renoirb** [comment]
![Victory!!](https://renoirboulanger.com/wp-content/themes/renoirb/assets/img/MagusVictory.gif)

I could finish a full build, including with the issue I outlined above.

![publican-rangerfinder-victory](https://cloud.githubusercontent.com/assets/296940/7594660/36edfe16-f8b0-11e4-994c-54339c3ca2a3.png)

**Comment by renoirb** [comment]
Here is a sample of the fact that I can build specs with the new Docker container. On the following screenshot, you’ll see a compiled version of the [w3c/rangefinder@dc51258 at a commit that has been made a few days ago](https://github.com/w3c/rangefinder/commit/dc51258b361e6b13fb508298065c2149dd6dab5b).

![publican-preview](https://cloud.githubusercontent.com/assets/296940/7600082/1a468276-f8d6-11e4-96fa-54e2ce1374c3.png)
