### ISSUE TITLE
Make source.webplatform.org managed by salt stack.

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#167]
For some time we had a Gerrit installation but its overkill for the size of the team (myself only, so far). We want a place where we have a local git mirror, backed up elsewhere as a compressed (and encoded?) archive outside of our network (a DreamObjects bucket?).
## Tasks
- [ ] Repository archive script
- [ ] Transfer over to S3/Swift bucket, only two versions script
- [ ] Make salt stack configuration script, including Gitolite

**Comment by renoirb** [comment]
Dropping the ball, we won’t use. Refer to webplatform/ops#177
