### ISSUE TITLE
Migrate webat25 to DreamCompute

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#168]
DreamHost wants their hardware ASAP, attempt to accommodate them without impacting the WWW Foundation.
## Tasks
- [x] Create new VM in DreamCompute
- [x] Re-install webat25.org site
- [x] Test if it works
- [x] Make switch on Fastly side
- [x] Change DNS A record for ExpressionEngine admin zone   (which we won’t advertize the URL here)

**Comment by renoirb** [comment]
Job is done. Also created a temporary VM that’ll redirect explicit requests on the ExpressionEngine admin zone to the new server IP directly. That way users who needs to access the control panel should be able to work regardless of the DNS propagation time.

**Comment by renoirb** [comment]
To do so I created small NGINX redirect block like this

```
    server_name HIDDEN.webat25.org;
    location ^~ /CMSADMINZONE {
      return 301 http://67.205.62.58$request_uri;
    }
    location / {
      return 301 http://www.webat25.org/;
    }
```
