### ISSUE TITLE
Rebuild webplatformstaging.org to latest config script refactor

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#174]
In order to do webplatform/ops#48; We have to make sure it works well in **webplatformstaging.org**, that it uses what's done in  [webplatform/ops](https://github.com/webplatform/ops), [webplatform/salt-basesystem](https://github.com/webplatform/salt-basesystem) repos, and issues webplatform/ops#121, webplatform/ops#171 so we can upgrade production.
## While working on this issue, ensure _those_ are handled
- [ ]  "Make Discourse have automatic database backup" webplatform/ops#154
- [ ] "Backup production ElasticSearch indexes directly into a DreamObjects bucket" webplatform/ops#120
- [ ] "Ensure ... are backed up and sent offsite" webplatform/ops#73

**Comment by renoirb** [comment]
Almost done.

**Comment by renoirb** [comment]
Make sure this issue is done prior to finish up webplatform/ops#48

**Comment by renoirb** [comment]
Dropped the ball, prioritizing on static site generator so we can shut down most of the infrastructure.
