### ISSUE TITLE
Make changes to drastically simplify site maintenance; Make blog and wiki to use static site generator

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#177]
We run with about 20 VMs. 14 of them are about sustaining possible load and to support both WordPress and MediaWiki.

Objective of this task is to **simplify** system infrastructure and maintenance.
## Tasks
- [ ] Export Wiki edit history into Git and make a static site generator version of the wiki (see [**webplatform/docs** README file](https://github.com/webplatform/docs) for progress report)
  - [x] Migration scripts and library in [webplatform/content-converter](https://github.com/webplatform/content-converter), and import script in [webplatform/mediawiki-conversion](https://github.com/webplatform/mediawiki-conversion)
  - [x] Content migrated in [webplatform/docs](https://github.com/webplatform/docs)
  - [x] WPD namespace in [webplatform/docs-wpd](https://github.com/webplatform/docs-wpd)
  - [x] Meta namespace in [webplatform/docs-meta](https://github.com/webplatform/docs-meta)
  - [ ] User profiles and old comments
- [ ] Export Blog content into a static site generator
- [ ] Refactor the homepage to use the same static site generator as the blog and wiki
- [ ] Rebuild only required servers
## VMs in use

| Quantity | Role name | Required only by blog/wiki/project |
| --- | --- | --- |
| 4 | _app_ | yes |
| 2 | _sessions_ | (incidental) yes |
| 2 | _redis_ | (incidental) yes |
| 2 | _db_ | (incidental) yes |
| 4 | _frontend_ | no |
| 1 | _blog_ | yes |
| 1 | _bots_ | no |
| 1 | _project_ | yes |
| 1 | _source_ | no |
| 2 | _docker_ | no |
| 1 | _stats_ | no |
| 2 | _elastic_ | no |
| 1 | _postgres_ | no |
| 1 | _salt_ | yes |
| 1 | _accounts_ | no |

Since we are’t going to host **[Discourse](http://discourse.wicg.io/)**, that we’ll shut down _project.webplatform.org_ to use GitHub issues, let W3C monitor the IRC channel, and stop using our own installation of Piwik we can also remove most of the infrastructure by this work item.

All that would be left is the static content, we might only really need only **[frontend, salt]**

**Comment by renoirb** [comment]
This should be closed, but since I'm going to write about it, here are a few links I had scattered around about this.

* [MediaWiki useful queries][gist-useful-mw-sql-queries]

[gist-useful-mw-sql-queries]: https://gist.github.com/renoirb/048eaee1d6aec3afa2e7 "MediaWiki useful queries"
