### ISSUE TITLE
Rework and Upgrade database server setup

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#20]
## Tasks
- [x] Ensure migration works for all components (Piwik, TheBugGenie, WordPress, MW, etc)
- [x] Figure out which to install, ask Dan from Wikimedia
- [x] Migrate all databases into new cluster using MariaDB 10.1
- [x] Figure out if we go with a Galera cluster (can send write to _any_ server) or keep same setup
- [x] Ensure every components gets the list of IP addresses of the database servers through Salt stack

**Comment by renoirb** [comment]
Might be related or duplicate of webplatform/ops#73

**Comment by renoirb** [comment]
Sent in "Work status update" email [on _devrel_ list](http://www.w3.org/mid/551464C7.8030908@w3.org)
