### ISSUE TITLE
Redeploy project ("BugGenie")  in new production environment

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#21]
Applies to upcoming staging infrastructure.

Not to prioritize automated deployment since we might move out of it to use GitHub issues and/or Phabricator
## Priorities
1. Ensure we deploy from more recent and compatible version
2. Ensure it looks the same as much as possible
3. Deployment by cloning and submodules
## Tasks
- [x] Upgrade Linux version to Ubuntu 14.04
- [x] Ensure migration of the data
- [x] Set in place local workspace (Vagrant VM?)
- [x] Check with @adobejulee which extensions we want
- [x] Ensure the theme is encapsulated and be added on top of clean checkout
- [ ] Ensure deployment work as is.

**Comment by renoirb** [comment]
This task already had 3d worth of work done. Deploying it as is.
