### ISSUE TITLE
4h — Rework WordPress setup and upgrade version

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#22]
## Tasks
- [x] Ensure we have wp-cli client
- [x] Use of nutcracker 
- [x] Fastly and SSL, rel #43
- [x] Create project that uses WordPress as submodule
- [x] Ensure we have ALL images in repo, some are in DreamObjects and others are elsewhere
- [x] Check for external images, they have to be all migrated in the project.
  - http://blog.webplatform.org/2013/04/doc-sprint-san-francisco-april-3/

**Comment by renoirb** [comment]
Deployed in Fastly, image references works. Its good to go.
