### ISSUE TITLE
Review site activity for traces of spam and make a report

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#3]
Prepare and organize things to check and take note to gather stats.
## Tasks
- [ ] Document how to make checks and what to put (metrics, hit counts, etc) in a recurring report
- [ ] Setup automatic task creation? (weekly)
- [ ] Create report template
- [ ] Setup location of published report. Wiki?
- [ ] Define checks to make

**Comment by renoirb** [comment]
Some work about how to assess if our defences are good are noted in a few issues:
- webplatform/ops#3
- webplatform/ops#118
- webplatform/ops#100
