### ISSUE TITLE
Make Fastly error messages less generic when its possible

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#40]
We could improve the project image with better descriptive error pages.

It has been observed that Fastly responds with a 503 error in contexts that we might want to serve a different message.

For example when:
- Connectivity problems between Fastly and Backend servers
- Backend server takes too long to respond with data
- etc.
## Tasks
- [ ] Improve ''static error pages'' when communication problem (other "guru meditation" left)
  - [ ]  Create human comprehensible explanation messages for each of them
  - [ ]  See [http://docs.fastly.com/guides/backend-servers/503-error-explanations Fastly specific errors documentation]
  - [ ]  See sample [http://www.webplatformstaging.org/errors/503.html 503 error page static version]
  - [ ]  Use static pages that are published in [GitHub www.webplatform.org project](https://github.com/webplatform/www.webplatform.org/tree/master/src/documents/errors src/documents/errors)
  - [ ] Find how to configure Fastly for each of them (i.e. When Fastly is about to serve white page error, replace with ours)
- Errors to cover
  - [ ] 503 Connection Refused,
  - [ ] 503 Network Unreachable; In case of a network outage between Fastly and DreamHost/iWeb networks
  - [ ] 503 Backend.max_conn Reached; When ALL backends cannot meet the demand
  - [ ] 503 Backend Is Unhealthy; When the only backend server isn’t "healthy"
  - [ ] 503 No Healthy Backends; When no backend server are’t "healthy"
  - [ ] 503 All Backends Failed or Unhealthy; When ALL backends aren’t "healthy"
  - [ ] 503 Backend Read Error; When backend server takes too long to respond
  - [ ] 503 Backend Write Error;
## Bookmarks
- http://www.one-tab.com/page/P14Zz3KjQZKqv6VukodRHA
- https://fastly.zendesk.com/requests/7140
