### ISSUE TITLE
Publish project salt-states

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#48]
All states should already have been rewritten to allow this so we can share our deployment code without any compromising information.
- Must be free of any private information such as passwords, IP addresses, or keys
- Ensure that each commit-er in the git history has matching current GitHub user aliases. If possible.
## Tasks
- [x] Rewrite any private data in history
- [x] Rewrite all authors to their current GitHub
- [x] Publish pillars and states
- [x] Get W3C systems team to host private data
- [x] push **private pillar** to W3C’s GitLab
- [x] push **mailhub configurations** to W3C’s GitLab
## Dependencies:
- webplatform/ops#49
- webplatform/ops#171

**Comment by renoirb** [comment]
Added webplatform/ops#171 as dependency so we can work on salt-states from a Vagrant VM. This new work item isn’t a big deal because I had plenty of bits and pieces to achieve this objective.

**Comment by renoirb** [comment]
Almost there.

**Comment by renoirb** [comment]
Done!
