### ISSUE TITLE
Some subdomains has issues w/ TLS

### ISSUE THREAD

**Issue by mathiasbynens** [webplatform/ops#60]
## Found issue
- [ ] https://project.webplatform.org/ redirects from HTTPS to HTT
- [ ] https://www.webplatform.org/ has mixed content
- [ ] https://webplatform.org/ gives an SSL connection error

Ref EFForg/https-everywhere/pull/621
## Tasks
- [ ] Ensure http://webplatform.org/... works

**Comment by renoirb** [comment]
Maybe we’ll defer `https://www.webplatform.org/ has mixed content` while working on webplatform/infrastructure-work#30

**Comment by renoirb** [comment]
Related to webplatform/ops#42

**Comment by renoirb** [comment]
This should be solved now. #TODO
