### ISSUE TITLE
Upgrade packages in current production and make a few spot checks

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#61]
## Task overview
- [x] Upgrade all production node packages
- [x] Remove whoopsie in production too
- [x] Ganglia still graphs data for each nodes
- [x] Is all services running, nothing unexpected in the logs?
## Hosts
- [x] accounts
- [x] deployment (+rebooted)
- [x] source (+rebooted)
- [x] piwik3 (+rebooted)
- [x] project2 (+rebooted)
- [x] monitor1 (+rebooted)
- [x] storage1 (+rebooted)
- [x] backup1 (+rebooted)
- [x] elastic1 (+rebooted)
- [x] bots1 (+rebuilt, +rebooted)
- [x] blog1
- [x] db4
- [x] percona1
- [x] app[7-11]
- [x] memcache9, 1, 2
- [x] specs
- [x] notes1
- [x] webat25
- [x]  mail (and rebooted)
## Procedure

Just to make sure everything works as is or fix manually. It will be resolved in new environment anyway.
1. Check if monitor is accessible with currently configured hostname
   
   ```
   ping -c 1 monitor.dho.wpdn
   ```
2. Upgrade package through salt (which also upgrades and restart salt-minion). From the salt master:
   
   ```
   salt foo pkg.upgrade
   ```
3. Commands on the machine itself:
   
   ```
   apt-get update;apt-get -y upgrade
   apt-get remove --purge -y whoopsie consolekit;apt-get autoremove -y
   ```

**Comment by renoirb** [comment]
* [ ] accounts
* [ ] deployment
* [ ] source
* [ ] piwik3
* [ ] project2
* [ ] monitor1
* [ ] storage1
* [ ] backup1
* [ ] elastic1
* [ ] bots
* [ ] blog1
* [ ] db4
* [ ] percona1
* [ ] app[7-11]
* [ ] memcache9, 1, 2
* [ ] specs

**Comment by renoirb** [comment]
Commands:
```
apt-get remove --purge whoopsie;apt-get autoremove -y
```

**Comment by renoirb** [comment]
Worked 1d

**Comment by renoirb** [comment]
Worked 1/2 day. Have to rebuild a few nodes before going back to continuing sprint.

**Comment by renoirb** [comment]
Innclude work described in #47

**Comment by renoirb** [comment]
Worked 1d. Last piece of current maintenance. Status post was at http://status.webplatform.org/post/108128779965
