### ISSUE TITLE
Automate Piwik (stats) deployment

### ISSUE THREAD

**Issue by renoirb** [webplatform/ops#81]
Following up what was described in [Milestone of end of January 2015](https://github.com/webplatform/ops/wiki/Milestone-of-end-of-January-2015).
## Tasks
- [x] Fastly and SSL, rel #43
- [x] Use Fastly’s GeoIP data instead of internal
- [ ] Automation setup, once figured out in webplatform/ops#80
## Expected workflow

```
git clone https://github.com/webplatform/FOO.git stats
cd stats
make
```
## Related
- webplatform/ops#80

**Comment by renoirb** [comment]
This should be done.
